### ISSUE TITLE
srt-generate fails when OpenAPI spec file contains header information

### ISSUE THREAD

**Issue by Jmcleodfoss** [Jmcleodfoss/simple-rest-tester#2]
srt-generator reports '`test['options'].headers.push` is not a function if the OpenAPI spec file contains a block like:

```yaml
    x-srt:
            responseRegexp: "response"
            expectation: "should complete the operation"
            options:
              headers:
                Authorization: "Basic base64-encoded-key-and-passcode"
```
